#include <iostream>
#include <math.h>
#include "mVector.h"
#include <random>

//Problem 58 (COMPLETE)
//Starting with 1 and spiralling anticlockwise in the following way, a square spiral with side length 7 is formed.

//					37 36 35 34 33 32 31
//					38 17 16 15 14 13 30
//					39 18  5  4  3 12 29
//					40 19  6  1  2 11 28
//					41 20  7  8  9 10 27
//					42 21 22 23 24 25 26
//					43 44 45 46 47 48 49

//It is interesting to note that the odd squares lie along the bottom right diagonal, but what is more interesting is that 8 out of the 13 numbers lying along both diagonals are prime; that is, a ratio of 8/13 ≈ 62%.
//If one complete new layer is wrapped around the spiral above, a square spiral with side length 9 will be formed. If this process is continued, what is the side length of the square spiral for which the ratio of primes along both diagonals first falls below 10%?

//NOTES
//o Rather than generating the Ulam Spiral again, use general formula to find values of diagonals (ignoring down right from center as they are square numbers (not prime))
// Diagonal entries emenating away from central 1 are generated by (2i+1)^2 - 6i, (2i+1)^2 - 4i, (2i+1)^2 - 2i

//Function which takes in a value and returns whether the input is a prime number (calculated by repeated division)
bool IsPrime(int TestValue){
	
	if(TestValue == 1){
		return false;
	}
	
	if(TestValue == 2){
		return true;
	}
		
	for(int i = 2; i <= pow(TestValue, 0.5); i++){
		if(TestValue % i == 0){
			return false;
		}
	}
	
	return true;
}


int main() {
	
	//Start with 3x3 ulam spiral as basecase
	int NumberOfPrimes = 3;
	int SideLength = 2;
	int CurrentDiagValue = 9;
	
	//Generate the values of the entries on the diagonals and determine whether they're prime, add to counter if so
	while((1.0*NumberOfPrimes)/(2*SideLength+1) > 0.1){
		SideLength += 2;
		for(int i = 0; i < 3; i++){
			CurrentDiagValue += SideLength;
			if(IsPrime(CurrentDiagValue)){
				NumberOfPrimes++;
			}
		}
		CurrentDiagValue += SideLength;
	}
	
	std::cout << "The size of Ulam Spiral where the ratio of primes falls below 10% is " << (SideLength+1) << "\n";
	
}
