#include <iostream>
#include <math.h>
#include <algorithm>
#include "mVector.h"

//Problem 5 (COMPLETE)
//2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
//What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

//NOTES
//o Try using unique prime factorisation theorem
//o Smallest number f(n) divided by exactly 1,...,n is f(n) = product(p_i^q_i) where p_i are primes and q_i are largest integer power such that p_i^q_i <= n.
//o Examples f(5) = 2^2 * 3 * 5 = 60, f(10) = 2^3 * 3^2 * 5 * 7 = 2520
//o Generate primes using Sieve of Sundaram

MVector GeneratePrimes(int MaxNumber){
	//Generate Primes (Sieve of Sundaram)
	int k = (MaxNumber-2) / 2;
	MVector IntegerList(k);
	MVector PrimesList(1);
	
	//Generate vector of 1 to MaxNumber
	for(int i = 0; i < k; i++){
		IntegerList[i] = i+1;
	}
	
	//Apply Sundaram conditions
	for(int i=1; i<=k; i++){
		for(int j=i; j <= (k-i)/(2*i+1); j++){
			IntegerList[i + j + 2*i*j - 1] = 0;
		}
	}
	
	//Save rescaled integers to PrimeList
	int IndexCounter = 1;
	
	for(int i = 1; i < k+1; i++){
		if(IntegerList[i-1] != 0){
			PrimesList.resizePlusOne();
			PrimesList[IndexCounter] = 2 * IntegerList[i-1] + 1;
			IndexCounter++;
		}
	}
	
	//Append 2 to start of PrimesList (Not generated by Sundaram Algorithm)
	PrimesList[0] = 2;

	return PrimesList;
}

int SmallestMultiple(int n){
	//Vector for returned PrimesList
	MVector PrimesList;
	//Add index n+1 to ensure if n is prime, it is added to the PrimesList. Required as problem states from 1 to n inclusive.
	PrimesList = GeneratePrimes(n+1);
	
	int f_n = 1;
	
	//Calculate f(n) as stated in notes
	for(int i = 0; i < PrimesList.size(); i++){
		int power = 1;
		while(pow(PrimesList[i],power) <= n){
			power++;
		}
		f_n *= pow(PrimesList[i],power-1);
	}
	return f_n;
}


int main() {
	//Input integer n, the largest number of 1,...,n for which you want to find the smallest multiple
	int n = 15;
	int f_n = 0;
	
	//Function Call
	f_n = SmallestMultiple(n);
	
	//Output
	std::cout << "The smallest integer evenly divisible by the numbers 1 to " << n << " is: " << f_n << "\n";
	
}
